CREATE TABLE IF NOT EXISTS history (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       query VARCHAR(255),
                                       result VARCHAR(255),
                                       time TIMESTAMP
);
insert into HISTORY(query, result, time) values ( 'test1','test1', LOCALTIMESTAMP())